### ISSUE TITLE
Command line usage on Windows 7: Error: read ENOTCONN 

### ISSUE THREAD

**Issue by dlandis** [julien-f/csv2json#3]
Hello,

I just tried to convert a file. Do you know what the issue is? Is the following supposed to work?

```
PS C:\csvs> .\node_modules\.bin\csv2json test.csv
x read ENOTCONN
Error: read ENOTCONN
    at exports._errnoException (util.js:746:11)
    at WriteStream.Socket._read (net.js:409:21)
    at WriteStream.Readable.read (_stream_readable.js:341:10)
    at WriteStream.Socket.read (net.js:314:43)
    at resume_ (_stream_readable.js:725:12)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

More info:
--I'm not using Cygwin
--Same error when input parameter is not included

**Comment by dlandis** [comment]
Ok, I see now it seems to work when an input and output file are both provided. That is the only way it works. Zero or one arguments it fails

**Comment by julien-f** [comment]
DId you try with the npm version or latest master?

**Comment by dlandis** [comment]
npm version. I can try to retest later with the latest changes

**Comment by julien-f** [comment]
Yes please, I changed some of the used libraries which may fix problem.

**Comment by julien-f** [comment]
@dlandis ping?
